### ISSUE TITLE
Compositor: Combine View Node

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#10]
- No “fallback” for default
- Autosyncing (ala renderlayers)

**Comment by dfelinto** [comment]
implemented as Switch View node

**Comment by fsiddi** [comment]
Looks great! Does the Update Views do anything special (I mean doesn't the compositor refresh automatically)?

**Comment by dfelinto** [comment]
As per design the compositor shouldn't do destructive changes without
consulting with the user.
(I remember a similar debate for the osl node).

Thus the idea of the update. Btw disable a view and update and the socket
will still be there but hidden. So you don't loose its connections.
