### ISSUE TITLE
Make Render View as shareable datablock

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#11]
To be discussed further with other developers, the goal is to make it easy to avoid typos and make the setup across scenes consistent.

Note: different shots still require different "datablocks"

**Comment by dfelinto** [comment]
This is on hold.
Meanwhile I will see if I can get the scene views to propagate to the other scenes while rendering (pipeline.c)

**Comment by dfelinto** [comment]
@fsiddi you mentioned that rendering linked scenes is not working. Could you please send me a sample file?

**Comment by fsiddi** [comment]
I made a new test file and at the moment liked scenes are working just fine! So there is no problem here.
