### ISSUE TITLE
CPU overused when 3-D is on

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#15]
We are always rendering the areas. Otherwise we get strange shadows from the menu, and some glitches after the splash screen (lack of redraw).

To prevent those bugs I'm not setting ar->do_draw to FALSE in one case. This is forcing the areas to redraw every time, thus the CPU overhad.

If someone can fix that, see "XXX Strange bug" in wm_draw.c::wm_method_draw_triple_stereo

**Comment by dfelinto** [comment]
Talked with Ton and now I know what the problem is.
Basically we can't copy the overlapped buffer back to the drawdata/drawdatastereo. So a quick solution is to store 2 more buffers to use to save the buffers after drawing

**Comment by dfelinto** [comment]
fixed, @fsiddi let me know if the problem is gone (if not, please re-open this issue)

**Comment by fsiddi** [comment]
It works great as long as you don't pan or zoom the Render Result in the UV/Image Editor.
In that case CPU gets overused again. Le me know if you can reproduce this.

**Comment by dfelinto** [comment]
It overheats _while_ you pan/zoom? Or _once_ you pan/zoom (meaning as soon as you do it there no way to calm the CPU down).

And can you make sure you don't have the save behaviour in trunk?

**Comment by fsiddi** [comment]
It overheats only while I pan/zoom. Once I stop panning or zooming goes
back to normal.
Same behavior does not happen in trunk.

**Comment by dfelinto** [comment]
@fsiddi do you still have this issue? (use official branch in git.blender.org for the test)

**Comment by dfelinto** [comment]
closing for now since I believe it's fixed.
