### ISSUE TITLE
Changes for Fullscreen modes

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#17]
When in clean full area we need a way to toggle the header (right now only the side panels have shortcuts)

**Comment by dfelinto** [comment]
Also: "Regarding the "clean fullscreen" name, maybe the old "fullscreen" can be renamed to "maximized" and "clean fullscreen" can be "fullscreen" then? Makes more sense to me."

**Comment by dfelinto** [comment]
UPDATE:
What was agreed on (talked with Brecht on that during bcon13):
- <b>Maximize Editor</b>: (old Ctrl+Up)
- <b>Full Screen Window</b>: (old Alt + F11)
- <b>Full Screen Editor</b>: new operator (currently implemented in multiview as 'SCREEN_OT_clean_full_area'). It should fullscreen the window regardless of the 3d mode, and make it clean. After exiting it, it should return to the previous window state (windowed/fullscreen). To use 'D' as the shortcut

That should be really easy to implement, given that the code is all there. We will still need the *_require_fullscreen function, so don't delete it, please.

**Comment by dfelinto** [comment]
NOTE: for that maximize Editor will be merged with the wm_stereo_toggle_exec operator.

If scene.use_multiviews handle the page flip thing (see code). Otherwise only do the old clean ui part of the functionality.

Always go to fullscreen.

**Comment by EibrielInv** [comment]
I'm taking a look to this, just looking the code to understand it...

**Comment by dfelinto** [comment]
This is implemented in https://developer.blender.org/D678
