### ISSUE TITLE
Viewport need to support 3-D

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#18]
(discussion started on #1 )

As for viewport, we don't need a toggle anymore. I think the "D" shortcut should be enough (it sets a flag in the window). As for 3-D only being available when we have left and right, we can have something similar to RE_HasStereo3D (but taking the active SceneRenderViews into account).

While at it, I think it may be better to not have the UI you are proposing ... Blender already has ways to switch between the cameras, not sure we want to add on top of that.

So wrapping up: [a] no UI at first, shows 3-D in viewport if:

((wmWindow.flag & WM_STEREO) && (U.stereodisplay != USER_STEREO_DISPLAY_NONE) && (hasrightviewactive && hasleftviewactive))

Or maybe only:
((wmWindow.flag & WM_STEREO) && (U.stereodisplay != USER_STEREO_DISPLAY_NONE))

[if you are too busy for that let me know and I see if I can take a look at it]

**Comment by Alexey-Akishin** [comment]
I'm OK to not have the UI, but I have not figured out yet how to implement this 3D support, it turned out to be harder than I thought. I decided to take a "break" and work on some other issues first. So feel free to work on this. Otherwise, I will try to return to this issue later...

**Comment by dfelinto** [comment]
ok. I will try to take a look at that.

**Comment by dfelinto** [comment]
implemented
