### ISSUE TITLE
Blue-Yellow is more popular then Yellow-Blue 

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#19]
According to Youtube:
http://www.pasteall.org/pic/show.php?id=52072

Mind changing that (UI and code)?
cheers

**Comment by Alexey-Akishin** [comment]
On YouTube "Blue-Yellow" is just a (wrong) label for Yellow-Blue scheme. Very recently I purchased Yellow-Blue glasses (I still prefer Green-Magenta, but at least I can actually test YB scheme), and "Blue-Yellow" mode in YouTube works well for Yellow-Blue glasses. By the way, if you do not have specific anaglyph glasses, if you choose Red-Cyan on YouTube, pause a video on a frame where Red-Cyan separation is obvious, and then switch to "Blue-Yellow", you will see that red becomes yellow, and cyan becomes blue - this also proves that YouTube implements Yellow-Blue scheme.

**Comment by dfelinto** [comment]
hm so I guess they decided to follow the R-G-B order.
If we implement the "swap eyes" it may be worthy implementing the changes.
For now I'll close the report.
