### ISSUE TITLE
we need rna tooltips for the 3d display types

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#21]
@fsiddi feel like tackling this one?

**Comment by fsiddi** [comment]
I would love to! I'll look into it in the next days.

**Comment by Alexey-Akishin** [comment]
@fsiddi, if you do not have enough free time to do this, I could do it.

**Comment by fsiddi** [comment]
Give me 2 more days to look into it. If I can't I'll let you know. Sounds
ok? If you are in a hurry no problem, just do it.

**Comment by Alexey-Akishin** [comment]
@fsiddi, sounds OK to me.

**Comment by fsiddi** [comment]
Ok I tried to look into it, but I don't have time for it unfortunately. So
feel free to take it away. Sorry :(

**Comment by Alexey-Akishin** [comment]
OK, I will do it (perhaps tomorrow or day after).
