### ISSUE TITLE
Sequencer - multiview/stereoscopic support

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#30]
Design problems:
- How to deal with mono strips? (i.e., do we need an equivalent of the "Switch Viewer" node?)
- How to automatically input a stereo strip? (e.g., should we take anything ending with _R and _L and group them together?)
- Should a scene strip have a "replace camera" for each view?
- ...

**Comment by fsiddi** [comment]
These are all interesting and important questions. I think mono strips could be always visible (independently from the channel used).
File input on the compositor is strange, so I'm not sure that grouping L and R would always work.

We should definitely have a chat about this at some point!

**Comment by dfelinto** [comment]
Closing this by now since sequencer is working on its own way. The design is open for changes of course, but to the point of being an open issue.
