### ISSUE TITLE
FSA render crash

### ISSUE THREAD

**Issue by fsiddi** [dfelinto/blender-multiview-old#32]
Just set up the default scene with FSA and a stereo pair, start rendering and it will crash. Is used to look incorrect a few revisions ago, but now it's really failing.

**Comment by dfelinto** [comment]
the original crash was due to a bug introduced after I fixed the Windows issue. But there is still a crash I believe

**Comment by fsiddi** [comment]
Yes I confirm that on OSX.

**Comment by dfelinto** [comment]
It only crashes when rendering with more than one thread by the way. I'm looking at a fix for that now.

**Comment by dfelinto** [comment]
You should get no more crashes. However in my test file here, I was only getting the right compo result when using FSA if I force an update in the nodetree.

**Comment by fsiddi** [comment]
Looks great now! Thank you for the fix! Now I can start working on Caminandes :)

**Comment by dfelinto** [comment]
Just so you know. Although there is no crash there is still a bug with FSA (as mentioned in the commit log)

**Comment by dfelinto** [comment]
FSA working 100% now :)

**Comment by fsiddi** [comment]
Awesome!
