### ISSUE TITLE
Move Views panel to Renderlayer panel

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#37]
> Does this need its own tab? Why not have a Views panel in the render layers tab? The dual lens camera icon is cool though.

I added as its own tab to help testers. I can move to renderlayer, no objections. I like the icon too :) it's used elsewhere, so no big deal not showing up in the top of the panel.

The other reason is that I thought we may want to completely hide/remove from the UI multiview functionality, thus having a panel only for that would be more clear.

**Comment by dfelinto** [comment]
Alexey, can you handle this one? No other change 
only the moving (Brecht suggested other ui changes but better do them separately).

Thanks

**Comment by Alexey-Akishin** [comment]
OK, will do it during this weekend.
