### ISSUE TITLE
Rename all the references from "3-D" to "3D"

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#39]
> Why name things "3-D" when we use "3D" everywhere else in Blender?

No strong reason, if Blender is using 3D elsewhere, 3D it is.

**Comment by Alexey-Akishin** [comment]
I will work on this today.

**Comment by Alexey-Akishin** [comment]
Done.

**Comment by dfelinto** [comment]
we should close only when the patch gets pulled. you can even refer the issue in the patch, so the issue gets closed automatically (github coolness) - https://help.github.com/articles/closing-issues-via-commit-messages ;)

**Comment by Alexey-Akishin** [comment]
OK.

**Comment by Alexey-Akishin** [comment]
It's merged. Closing.

**Comment by dfelinto** [comment]
thanks I thought my edit in the pull-request comment would have close this entry, but apparently not.
thanks for the patch
