### ISSUE TITLE
User preference 3D display options tweaks

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#41]
- The label in the user preferences should be "3D Stereo Display" instead of "3-D Display" since we only support that at the moment.
- There should be a default 3D display mode selected in the user preferences I think, not sure why there is a None option.

**Comment by Alexey-Akishin** [comment]
I will work on this tomorrow.

**Comment by dfelinto** [comment]
I think to add a reference to the issue not necessarily closes it. Not sure, closing it now, thanks Alexey.
