### ISSUE TITLE
Missing Interlaced methods

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#5]
The same way we have multiple anaglyph options, we will need the following interleaved methods:
- Row Interlaced (current method, also commonly known as horizontal interleave)
- Column Interlaced (aka vertical interleave)
- Checkerboard Interlaced

(note: I'm confused on whether to use interleaved or interlaced as UI names)

**Comment by Alexey-Akishin** [comment]
```
I will try to implement these methods tomorrow.
```

**Comment by dfelinto** [comment]
Also, for those methods we will need a "swap eye" option. I don't think there is a standard on which line/column goes first (as in whether it is left or right). I may be wrong though.

The same "swap eye" may be useful elsewhere (e.g. anaglyphs?) so the name could be generic (or better, to be a U.stereo_flag).

**Comment by Alexey-Akishin** [comment]
I implemented missing interlaced methods. I will work on adding option to swap left/right stereo channels tomorrow.

**Comment by dfelinto** [comment]
pushed your patch, closing the issue
