### ISSUE TITLE
Build instructions for Linux

### ISSUE THREAD

**Issue by fsiddi** [dfelinto/blender-multiview-old#59]
Could we get some instructions on how to compile the multiview branch on Linux? I tried to combine the steps for OSX and the linux dependency script and it did not end up well. Specifically, I'm trying to build the multiview_caminandes branch to complete the Caminandes stereo project.

Thanks :)

**Comment by dfelinto** [comment]
Alexey can you help with that?
I believe next week I will resume working on the branches btw

**Comment by Alexey-Akishin** [comment]
I have used install_deps.sh script. I remember that I had some minor problems compiling but few simple workarounds solved them. Unfortunately I don't remember exact steps. Francesco, post what you did and what errors you got. If it's the same problem I encountered I will tell you what I did to solve it.

dfelinto, hopefully next week I will resume working on it too, but probably at the weekend.

**Comment by fsiddi** [comment]
Hey Alexey!
this is the error. Looks like the usual openEXR nightmare.

```
Linking C static library ../../../../lib/libbf_rna.a
[ 43%] Built target bf_rna
[ 54%] Built target bf_compositor
[ 54%] Building CXX object source/blender/imbuf/intern/openexr/CMakeFiles/bf_imbuf_openexr.dir/openexr_api.cpp.o
/home/fsiddi/blender/branches/multiview/blender/source/blender/imbuf/intern/openexr/openexr_api.cpp:98:27: fatal error: ImfPartHelper.h: No such file or directory
compilation terminated.
make[2]: *** [source/blender/imbuf/intern/openexr/CMakeFiles/bf_imbuf_openexr.dir/openexr_api.cpp.o] Error 1
make[1]: *** [source/blender/imbuf/intern/openexr/CMakeFiles/bf_imbuf_openexr.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dfelinto** [comment]
@fsiddi you need to manually copy this file (ImfPartHelper.h) to the installer folder of Imbuf/Openexr

**Comment by fsiddi** [comment]
That worked, thank you so much! 
Any reason why this happened?

**Comment by dfelinto** [comment]
It's a bug in the cmake install files of imbuf (so OpenEXR bug)
