### ISSUE TITLE
Basic/Advanced Stereo

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#65]
Those are big changes in 'Views' that should be done before some of the other issues can be tackled.

Views now should have an enum to pick <b>Basic Setup</b> and <b>Advanced Setup</b>.
Basic setup will let you enable the individual L/R views, and pick a suffix for when exporting the views.

Advanced setup will let you have more than 2 views, and for each view you can pick a <b>Camera Suffix</b>. This way you can have different camera rigs (e.g., Wide_L, Wide_R, Wide_C, Far_L, Far_R, Far_C) and change between them by simply changing the current scene->camera. It will also work with markers and camera binders.

<b>Basic Setup</b>
- Left   [v]
- Right [v]

[v] Custom Suffix [ _L ]

<b> Advanced Setup</b>
- Left   [v]       +
- Right [v]       -

Camera Suffix [ _L ]
[v] Custom Suffix [ _L ]

So no more 'builtin-camera' Center/Left/Right selection.

**Comment by dfelinto** [comment]
Update,

**Comment by dfelinto** [comment]
Proposal for changes on suffixes:
https://db.tt/K7GJdvFi

@fsiddi do you like it?

**Comment by fsiddi** [comment]
Looks great to me :)

**Comment by dfelinto** [comment]
Basic/advanced fully working at the moment
