### ISSUE TITLE
Window Manager General Drawing Problems

### ISSUE THREAD

**Issue by EibrielInv** [dfelinto/blender-multiview-old#69]
Related to #15 

After enabling Stereoscopy the window is not refreshing properly. Menus overlaps, some mouse events not being handled, or values changes not firing proper redraw.
- Changing to camera don't refresh until you change some parameter
- Writing a number in field don't show the last number entered
- Moving, rotating entering value with numpad don't show the translation or rotation of the object for last number entered. (pressing R, then 4, then 5, show the object rotated 4º instead of 45).
- When looking through a camera in a View3D area, other View3D areas freezes.

With Stereoscopy disabled, the same happens, but in a less noticeable level.
With a GForce card the same happens, but in a less noticeable level.

Ubuntu Linux 12.04, with ATI Mobility Radeon HD 4250 Graphics

![drawingerrors](https://f.cloud.github.com/assets/172656/1460173/84916ea8-4418-11e3-90e8-e191b18bdff8.png)

**Comment by dfelinto** [comment]
I´m aware of this. it´s related to the #15 indeed and it´s caused from the stereo implementations in wm_draw.c and wm_stereo.c (the triplebuffer thing)

**Comment by EibrielInv** [comment]
Works way better now :D

**Comment by dfelinto** [comment]
Fixed
