### ISSUE TITLE
Epilepsy Mode

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/blender-multiview-old#7]
1. mode should be renamed "Dr. Epilepsy".
2. it would be more efficient if we had a slider to set the time interval. (time based). Right now it's a bit random.

**Comment by Alexey-Akishin** [comment]
```
I will work on this after #5.
```

**Comment by dfelinto** [comment]
Pushed the patch, thanks. For epilepsy (and probably for time-sequential) we may need to force update of the ui, otherwise image editor doesn't seem to update. but that's for later.

For now it would be better if the range was a bit different. 10 sec is too much, while 0.1 is almost not fast enough.
My suggestion would be: 0.05 to 1 as UI limits, and 0.01 to 5 as hard limits, what do you think?
(also I would probably name the property interval or frequency instead of delay).

**Comment by fsiddi** [comment]
If Dr. Epilepsy is not available in the Image Editor, were can I see it? I can't see it in 3D Viewport too...

**Comment by Alexey-Akishin** [comment]
I suggest to keep 10 sec as max hard limit. I think sometimes I may want to set it high, especially for rendered images, so I could see left and right views as slideshow at typical speed. Renaming "delay" to interval sounds like a good idea. I sent a pull request with these changes. But we do not have default value yet...

**Comment by dfelinto** [comment]
@fsiddi if you click with the mouse multiple times you should see it.
We need to investigate why. We may need to force an update of the ui when there is no mouse 
(and I think time-sequential has the same problem)

**Comment by fsiddi** [comment]
Yeah, I noticed that moving the mouse over any button triggers a full interface update too. Will wait for the fix, no hurry :)

**Comment by dfelinto** [comment]
For the records, the coolest way of using this mode is using alt+a in the Image Editor ;)
At some point we may want to rename this mode to 'Software Time Sequential' which I think may be the 'correct' term.

**Comment by dfelinto** [comment]
And the Dr. Epilepsy mode is gone . . . R.I.P. a1a5bff
