### ISSUE TITLE
Draw Stereo Camera

### ISSUE THREAD

**Issue by EibrielInv** [dfelinto/blender-multiview-old#70]
Stereo Camera need to Draw properly on View3D.
- Must show Interocular Distance
- Must show Convergence Distance (Parallel?)
- Must show Near & Far Planes (proposal)
- Convergence Plane must have lines crossing it, to show easily intersection on objects.

Near & Far planes need 2 parameters to show correctly Far Plane Separation (percent) and Near Plane Separation (percent. This values can be set on code, but I don't recommend that.

Work so far (ugly design) Youtube Video: http://www.youtube.com/watch?v=U9nE5ecDFok&feature=youtu.be

![drawcamera](https://f.cloud.github.com/assets/172656/1461124/cfd84fd6-4494-11e3-844a-b09a1987416f.png)

**Comment by EibrielInv** [comment]
Some improvements:

![camdraw2](https://f.cloud.github.com/assets/172656/1462297/c0fc5d9e-44ef-11e3-8eb3-20b5b6a48e2c.png)

**Comment by dfelinto** [comment]
this is already implemented, closing now
