### ISSUE TITLE
Stereo Camera & Stereo View3D

### ISSUE THREAD

**Issue by EibrielInv** [dfelinto/blender-multiview-old#71]
View3D must show properly the influence of Stereo Parameters:
- Convergence Distance
- Interocular Distance
- Shift (Proposal, to change Budget position, "Shift" isn’t the best name)

Work so far: http://www.youtube.com/watch?v=GKVzVHaqkCo&feature=youtu.be

![view3dstereo](https://f.cloud.github.com/assets/172656/1461129/b7c2081e-4495-11e3-819d-d71869d120c4.png)

**Comment by dfelinto** [comment]
What am I seeing in this demo?
Technically the viewport should show in 3d only when you are inside the camera viewport.
For the other views (e.g., when in quad view) you will see the ´planes´, cameras, ... but not stereo itself).

**Comment by EibrielInv** [comment]
For some reason when I press "D" all viewports show stereo, and viewports not showing a Camera are locked.
Let me know if it's a bug of my implementation.

**Comment by dfelinto** [comment]
A did a bunch of updates. Once we have the #17 done we can reassess this one.

**Comment by dfelinto** [comment]
@Eibriel can we close this? I believe viewport is showing the 3d correctly now

**Comment by dfelinto** [comment]
@Eibriel can we close this? I believe viewport is showing the 3d correctly now
