### ISSUE TITLE
Camera Fixed to first one

### ISSUE THREAD

**Issue by EibrielInv** [dfelinto/blender-multiview-old#72]
- Open Blender
- Delete Camera
- Create Camera
- Set camera as active (Ctrl+0)
- Set view to camera (0)
- [The viewport show the new camera view]
- Enable 3D, on panel
- Enable 3D on viewport (D)
- [The viewport show the old camera view]

Switching 3D view with D will switch between old camera view and new camera view.

Real camera position:
![newcamera](https://f.cloud.github.com/assets/172656/1462498/cd3bcb70-44fa-11e3-9b4a-5c242f05c01a.png)

Camera position while 3D view is active:
![oldcamera](https://f.cloud.github.com/assets/172656/1462500/da68ad18-44fa-11e3-9f34-695e126468ed.png)

**Comment by dfelinto** [comment]
Why to delete and create a new camera?
Check the changes we do in readfile.c, it can probably be expanded to what you need.

And are you always showing the planes? I think it should follow the viewport stereoscopy 'show planes' option.

Nice progress by the way

**Comment by EibrielInv** [comment]
Some times you want to delete the default camera and append a Camera Rig (with its own camera), I think it's an operation that must be allowed freely.

I'll look to readfile.c!

Yes Its always showing, I'll add a check for 'show planes' and if stereo is on.

Thanks!

**Comment by dfelinto** [comment]
Ah that was for an 'Advanced Stereo' setup. I thought it was for the Basic one

**Comment by EibrielInv** [comment]
Here is a video showing the issue :
http://www.youtube.com/watch?v=jIxppIxzdLs

**Comment by dfelinto** [comment]
I think this is fixed. Please test it again and if it works close the bug

**Comment by EibrielInv** [comment]
Fixed!!
