### ISSUE TITLE
Motion Blur for Cycles is broken for Advanced Stereo and multiple Cameras

### ISSUE THREAD

**Issue by maverick1999** [dfelinto/blender-multiview-old#79]

**Comment by dfelinto** [comment]
Can you share a sample file, please?

**Comment by maverick1999** [comment]
https://www.dropbox.com/s/lnvebgnu8snfear/_mblur_multiview_bug.blend?dl=0

**Comment by maverick1999** [comment]
should be the other way around, monkeys should be blurred and not the cube

**Comment by dfelinto** [comment]
File also here: http://www.pasteall.org/blend/31277

**Comment by dfelinto** [comment]
Bug fixed, thanks for reporting it :)
