### ISSUE TITLE
Passes are not working

### ISSUE THREAD

**Issue by maverick1999** [dfelinto/blender-multiview-old#81]
1.Passes are either not saved or not imported correctly on OpenEXR Multiview
2.Passes seem to be rendered for just a single camera
3.When importing an OpenEXR Multiview image in the Compositor there could be another option called Pass below the Layer and View dropdown lists.

Generally Passes are not functional at this point

**Comment by dfelinto** [comment]
That should be fixed now (in rev. 610a66bf8c547d084e61aac338976e3f312ee3c4 ). Both exporting and importing of OpenEXR Multiview files should be working.
