### ISSUE TITLE
Anaglyph color is wrong for active wireframe objects

### ISSUE THREAD

**Issue by foobarbecue** [dfelinto/blender-multiview-old#89]
The color of active objects is set by the Themes in the user preferences. In Anaglyph mode, the color chosen for Active Object is not modified for the red / blue filters. This makes it very hard to edit anything in anaglyph mode.

**Comment by foobarbecue** [comment]
Actually, maybe I'm wrong about this. It seems to be working. It might just be a problem with Weight paint.

**Comment by dfelinto** [comment]
Alright, closing then ;) At least for now.
